INSERT INTO communityOnAir.cities (city_name) VALUES ("San Francisco");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Chicago");
INSERT INTO communityOnAir.cities (city_name) VALUES ("New York");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Austin");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Seattle");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Boston");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Miami");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Detroit");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Los Angeles");
INSERT INTO communityOnAir.cities (city_name) VALUES ("Nashville");